# Configuration for NoDupePlugin

# List of high-vulnerability items (by Material name)
# Example: SHULKER_BOX, BLACK_SHULKER_BOX, etc.
high-vulnerability-items:
  - SHULKER_BOX
  - WHITE_SHULKER_BOX
  - ORANGE_SHULKER_BOX
  - MAGENTA_SHULKER_BOX
  - LIGHT_BLUE_SHULKER_BOX
  - YELLOW_SHULKER_BOX
  - LIME_SHULKER_BOX
  - PINK_SHULKER_BOX
  - GRAY_SHULKER_BOX
  - LIGHT_GRAY_SHULKER_BOX
  - CYAN_SHULKER_BOX
  - PURPLE_SHULKER_BOX
  - BLUE_SHULKER_BOX
  - BROWN_SHULKER_BOX
  - GREEN_SHULKER_BOX
  - RED_SHULKER_BOX
  - BLACK_SHULKER_BOX

# Enable or disable debug logging
debug: false

# Notify the offending player when duplicates are detected
notify-player: false

# Automatically remove duplicated items when detected
remove-duplicates: false

# Enable or disable the /simdupe command. Should only be enabled for testing!
enable-simdupe: false

# Estimated number of concurrent players on the server
estimated-concurrent-players: 30

# Minimum and maximum interval for inventory checks (in seconds)
min-inventory-check-interval: 30
max-inventory-check-interval: 120

# Scan container blocks for duplicate items
scan-containers: true

# Notify staff with permission "nodupe.alerts" when duplicate items are found
enable-duplicate-alerts: true

# Log duplicate alerts to "dupe-alerts.log"
log-duplicate-alerts: true
